name: blog
description: A simple static site showcasing jaguar_martini's features.
version: 0.0.1
homepage: https://jaguar-dart.github.io/
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  jaguar_martini: # ^1.4.1
    path: ../../martini
  stencil:
  date_format: ^1.0.2

dev_dependencies:
